language: r
cache: packages
r:
- bioc-release
r_github_packages:
- hadley/pkgdown
r_packages:
- packagedocs
r_github_packages:
- GreenleafLab/chromVARmotifs
- GreenleafLab/chromVAR
before_install: if [[ "$TRAVIS_R_VERSION_STRING" = 'bioc-devel' ]]; then mkdir ~/.R
  && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi
before_script: echo "BiocParallel::register(BiocParallel::SerialParam())" > ~/.Rprofile
addons:
  apt:
    packages:
    - libgsl0ldbl
    - libgsl0-dev
r_check_args: --no-vignettes --no-build-vignettes
after_success:
- if [[ "$TRAVIS_R_VERSION_STRING" = 'bioc-devel' ]]; then R CMD INSTALL *tar.gz; fi
- if [[ "$TRAVIS_R_VERSION_STRING" = 'bioc-devel' ]]; then Rscript -e "packagedocs::deploy_travis(repo = 'caleblareau/gchromVAR', build_fn = function(output_dir, ...){pkgdown::build_site(path = output_dir, examples = FALSE)})"; fi
